version: '3.1'

#my-app:
   #image: ${docker-registry}/my-app:3.0
   #ports:
   #- 3000:3000

services:
  mongo:
    image: mongo
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin1
    - MONGO_INITDB_ROOT_PASSWORD=secret1
    ports:
    - '27017:27017' 

  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin1
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret1     
      - ME_CONFIG_MONGODB_URL=mongodb://admin1:secret1@mongo:27017
    depends_on:
      - mongodb
  #volumes:
    #mongo-data:
      #driver: local
